### ISSUE TITLE
Update "We Hiring" Pane

### ISSUE THREAD

**Issue by tyronegrandison** [CommerceDataService/DataService_WebSite#3]
Change it to "Our team" profiles.

**Comment by tyronegrandison** [comment]
@radhikabhatt26 @dcwebmaven 

Change it to the Types of People we have on board and Profile Pics and descriptions of everyone.

**Comment by radhikabhatt26** [comment]
Suggestions:
- have someone(Jeff) take headshots for the team so we all have the same photos
- have some interactivity when scrolling over headshots 
- for description, have job title + plus fun fact? (See https://18f.gsa.gov/team/)

@tyronegrandison @dcwebmaven

**Comment by tyronegrandison** [comment]
Yes @radhikabhatt26

**Comment by dcwebmaven** [comment]
Great ideas @radhikabhatt26! Why don't you make a couple of mock ups of some potential layouts for the profile page?

Sent via smartphone.

**Comment by radhikabhatt26** [comment]
Question - I was talking with Jeff, and he mentioned that @dcwebmaven might be interested in getting rid of the bootstrap code we've used and instead build the whole site in Drupal. I'm not familiar with Drupal, so if that is the case, I'll need to learn the capabilities of Drupal. 

I can create some mockups, and I've already done work editing the Bootstrap theme we have in place. If we are going to get rid of this theme entirely, it would be helpful to know that now, so I can create mockups/additional options for this site if and/or when we decide to move to Drupal to build the site. 

@tyronegrandison @dcwebmaven let me know what you think! Thanks!

**Comment by radhikabhatt26** [comment]
I've made a mockup for the "Meet the Team" section using Invision, which can be accessed here: https://invis.io/NG5QILXY8

In the "Meet the Team" section, my image and Alison's image are clickable. I've also left comments on different sections. I've also forked the code and changed the layout some- this mockup shows my ideas for things I could not code/will need help with coding.

I've realized after working on this, we need to discuss the prioritization of content, regarding old content with new content we want to add, in order to move forward with edits to this site. Hopefully we can do that this week. @tyronegrandison @dcwebmaven
